use_frameworks!

platform :ios, '8.0'

target 'wildAllParamPicKit_Example' do
  pod 'wildAllParamPicKit', :path => '../'

  target 'wildAllParamPicKit_Tests' do
    inherit! :search_paths

    
  end
end
