desc '首次起飞，注意避让'
lane :wildPicViewKit do |options|

tagNum = options[:tag]
podspecName = options[:specName]

cocoapods(
	clean: true,
	podfile:"./Example/Podfile"
)

git_add(path:".")
git_commit(path:".", message:"upgrade repo")
push_to_git_remote

remove_git_tag

add_git_tag(
	tag:tagNum
)

push_git_tags

pod_lib_lint(allow_warnings:true)

pod_push(path:"./#{podspecName}.podSpec", repo:"wildSpecs")

end